travis:
  secure:
    BINSTAR_TOKEN: VzhEGpFKB66VIyZUez8l6hH/gC5zUGSFMxtFlnWiXN87dsSSmDLGq5ZDUs6EAOT+lVoZKgmcEsMMFd6Q504fyxsraukNtXGX4FAbyzAEcqmSO3SONxqwfwLAiJ+ivkLwVh18VLpRm5xnx8oqfW7bnx3bN9u0fFYEsv0egaAm7ZZ3TTdW8o9U+gGA9cj9WoZ1vTKX28hSur1qokrpARYh50/C+WUv411D7jHBOlJX6fosjlpYaDZYx9dLKQba/YQBXDANWh3W33U0sKmihlRet5hoAqMyzH88/9a7f19ohC/O+hGJrxisE6S2xAOdf3EuOQZ+p3B7a2Z4wJ3TDyzwkjNry7uka6hZrezHBSojHAEuzBwoDUZX3pw10GplKhH0EjcM0hYU9es7vU/qR2vtGGie1Adw+fZAg5C1lzqINYylvOhw9cl7Bdz3gYwsi8K/QAT0p2p1Uj0nshOq31/0mwAcY4jl8NvG4fzxROcLdGFYAhoSVGOyh9aPNF08kMnT57ubo6abVe61LMq67zsim43p7MahWgQ8+nZp9R2tvUugPMd39qyMeSPkETr/n8W7V6XDc4FiO5785SMyXDp6CDqFXAOLqqaVvLsCa+kpYzMaHEgTAWRU8TOFwnjyQ4jE9xaoBKX/BfB+EzSTFQueWVfKmb+CcKcc7SXqS1PMC2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
